"""
/fairness — Provably Fair info panel + in-Discord verification tool.
"""

import discord
import hashlib
import hmac as _hmac
from discord import app_commands
from discord.ext import commands
from discord.ui import View, Select, Modal, TextInput

from modules.constants import FOOTER_TEXT


# ─── Per-game explanation data ────────────────────────────────────────────────

_GAMES = {
    "overview": {
        "label": "🔐 How It Works (Overview)",
        "emoji": "🔐",
        "title": "🔐 Provably Fair — Overview",
        "color": 0x5865f2,
        "desc": (
            "Every game outcome is **mathematically verifiable** — we can never "
            "manipulate results because they are determined before you even play.\n\n"
            "**The 3 ingredients:**\n"
            "🔑 **Server Seed** — A secret random string generated by us. "
            "Only its **SHA-256 hash** is shown before the game starts.\n"
            "🪪 **Client Seed** — Your personal seed (auto-generated, changeable). "
            "Ensures you influence the outcome.\n"
            "🔢 **Nonce** — A counter that increases by 1 every game, so the same seeds "
            "never produce the same result twice.\n\n"
            "**How a result is made:**\n"
            "```py\n"
            "HMAC-SHA256(server_seed, \"client_seed:nonce\")\n"
            "→ 32-byte digest split into 8 floats [0, 1)\n"
            "→ floats are mapped to the game outcome\n"
            "```\n"
            "**After the game:**\n"
            "✅ The real server seed is revealed in the PF log channel.\n"
            "✅ You can verify: `SHA-256(server_seed) == hash shown before game`\n"
            "✅ You can recompute the exact floats and replay the result.\n\n"
            "> Use the **🔎 Verify a Result** button below to check any game yourself."
        ),
    },
    "roulette": {
        "label": "🎡 High To Win (Roulette)",
        "emoji": "🎡",
        "title": "🎡 High To Win — Provably Fair",
        "color": 0xe74c3c,
        "desc": (
            "**How the result is determined:**\n"
            "Two floats from the HMAC digest are used — one for you, one for the house.\n\n"
            "```py\n"
            "float[0] × 37 → your spin   (0 – 36)\n"
            "float[1] × 37 → house spin  (0 – 36)\n"
            "```\n"
            "🟢 **Win** → your spin > house spin\n"
            "🔴 **Lose** → your spin < house spin\n"
            "🟡 **Tie** → equal spins → bet returned\n\n"
            "**Multiplier:** `1.90×`\n\n"
            "**Verification example:**\n"
            "> Compute `HMAC-SHA256(server_seed, \"client:nonce\")`, take first 8 bytes "
            "as float[0] and next 8 as float[1], multiply both by 37 and floor. "
            "Compare with the logged values."
        ),
    },
    "dice": {
        "label": "🎲 Dice",
        "emoji": "🎲",
        "title": "🎲 Dice — Provably Fair",
        "color": 0x3498db,
        "desc": (
            "**How the result is determined:**\n"
            "Two floats from the HMAC digest are converted to dice rolls (1–6).\n\n"
            "```py\n"
            "float[0] × 6 + 1 → your roll   (1 – 6)\n"
            "float[1] × 6 + 1 → house roll  (1 – 6)\n"
            "```\n"
            "🟢 **Win** → your roll > house roll\n"
            "🔴 **Lose** → your roll < house roll\n"
            "🟡 **Tie** → equal rolls → bet returned\n\n"
            "**Multiplier:** `1.90×`\n\n"
            "**Verification example:**\n"
            "> Recompute HMAC, take `floor(float[0] * 6) + 1` and "
            "`floor(float[1] * 6) + 1`. Compare with the log."
        ),
    },
    "coinflip": {
        "label": "🪙 Hot & Cold",
        "emoji": "🪙",
        "title": "🪙 Hot & Cold — Provably Fair",
        "color": 0xf39c12,
        "desc": (
            "**How the result is determined:**\n"
            "A single float from the HMAC digest decides the house's pick.\n\n"
            "```py\n"
            "float[0] >= 0.5 → House picks  Cold ❄️\n"
            "float[0] <  0.5 → House picks  Hot  🔥\n"
            "```\n"
            "🟢 **Win** → your pick matches the house pick\n"
            "🔴 **Lose** → your pick doesn't match\n\n"
            "**Multiplier:** `1.90×`\n\n"
            "**Verification example:**\n"
            "> Compute HMAC, read first 4 bytes as a big-endian uint32, "
            "divide by 2³² → float. If ≥ 0.5 house chose Cold, else Hot."
        ),
    },
    "mines": {
        "label": "💣 Mines",
        "emoji": "💣",
        "title": "💣 Mines — Provably Fair",
        "color": 0x2ecc71,
        "desc": (
            "**How the mine positions are determined:**\n"
            "The 5×4 grid (20 cells) is shuffled using a **Fisher-Yates** algorithm "
            "seeded by the HMAC digest.\n\n"
            "```py\n"
            "4 HMAC rounds are used:\n"
            "  HMAC(server_seed, \"client_seed:nonce:0\") → 8 floats\n"
            "  HMAC(server_seed, \"client_seed:nonce:1\") → 8 floats\n"
            "  HMAC(server_seed, \"client_seed:nonce:2\") → 8 floats\n"
            "  HMAC(server_seed, \"client_seed:nonce:3\") → 8 floats\n"
            "= 32 floats total\n\n"
            "Fisher-Yates shuffle on cells [0..19]\n"
            "→ first N cells become mines\n"
            "```\n"
            "This guarantees the entire board is fixed before your first click. "
            "No mine can be moved after the game starts.\n\n"
            "**Multiplier:** increases with each safe cell revealed.\n"
            "Formula: `(1 - house_edge) × C(20, k) / C(20 - mines, k)`\n"
            "where `k` = diamonds uncovered so far."
        ),
    },
    "crystals": {
        "label": "💎 Crystals",
        "emoji": "💎",
        "title": "💎 Crystals — Provably Fair",
        "color": 0x9b59b6,
        "desc": (
            "**How the 5 crystals are determined:**\n"
            "Each of the 5 crystal positions is assigned a type using one float per crystal.\n\n"
            "```py\n"
            "float[0] → crystal 1 type\n"
            "float[1] → crystal 2 type\n"
            "float[2] → crystal 3 type\n"
            "float[3] → crystal 4 type\n"
            "float[4] → crystal 5 type\n"
            "```\n"
            "Each float is multiplied by the number of crystal types and floored to get the index.\n\n"
            "**Winning combinations:**\n"
            "💠 One Pair → small multiplier\n"
            "⭐ Two Pair → better\n"
            "✨ Triple → good\n"
            "💫 Full House → great\n"
            "🔥 Quadruple → rare\n"
            "🌟 Quintuple → legendary\n\n"
            "The full board is determined before you click any crystal."
        ),
    },
    "towers": {
        "label": "🗼 Towers",
        "emoji": "🗼",
        "title": "🗼 Towers — Provably Fair",
        "color": 0x1abc9c,
        "desc": (
            "**How the bomb position per floor is determined:**\n"
            "Each floor has exactly 1 bomb. Its column position is picked using one float per floor.\n\n"
            "```py\n"
            "float[floor_index] × num_columns → bomb column (floored)\n"
            "```\n"
            "- **Easy** mode: 3 columns per floor (1 bomb, 2 safe)\n"
            "- **Medium** mode: 2 columns per floor (1 bomb, 1 safe)\n"
            "- **Hard** mode: 2 columns per floor, 8 floors\n\n"
            "All bomb positions are fixed before your first move. "
            "The multiplier grows as you climb higher floors safely.\n\n"
            "**Max multiplier** varies by mode — up to `~100×` on hard with all floors cleared."
        ),
    },
    "limbo": {
        "label": "🚀 Limbo",
        "emoji": "🚀",
        "title": "🚀 Limbo — Provably Fair",
        "color": 0xe91e63,
        "desc": (
            "**How the result multiplier is calculated:**\n"
            "A single float is converted into a multiplier using the house edge.\n\n"
            "```py\n"
            "float[0] = first 4 bytes of HMAC digest / 2³²\n\n"
            "result = (1 - 0.10) / float[0]\n"
            "       = 0.90 / float[0]\n"
            "       (minimum 1.00×)\n"
            "```\n"
            "🟢 **Win** → result >= your target multiplier\n"
            "🔴 **Lose** → result < your target multiplier\n\n"
            "**Win chance formula:**\n"
            "`win_chance = 0.90 / target_multiplier`\n\n"
            "**Examples:**\n"
            "| Target | Win Chance |\n"
            "|--------|------------|\n"
            "| 1.50×  | 60.00%     |\n"
            "| 2.00×  | 45.00%     |\n"
            "| 10.00× | 9.00%      |\n"
            "| 100×   | 0.90%      |\n\n"
            "**Verification:** recompute `0.90 / float[0]` — compare with the logged result."
        ),
    },
    "case_opening": {
        "label": "📦 Case Opening",
        "emoji": "📦",
        "title": "📦 Case Opening — Provably Fair",
        "color": 0xf5a623,
        "desc": (
            "**How the item is selected:**\n"
            "Each item has a **weight** inversely proportional to its value "
            "(rarer = more expensive = lower weight). "
            "A float is mapped onto the weighted distribution.\n\n"
            "```py\n"
            "weight[item] = 1 / item_value\n"
            "total_weight = sum of all weights\n\n"
            "float[i] × total_weight → position on weight axis\n"
            "→ walk cumulative weights until we pass position\n"
            "→ that item is the winner\n"
            "```\n"
            "For **multiple cases** opened at once:\n"
            "`float[0]` → case 1, `float[1]` → case 2, etc.\n"
            "If more than 8 cases, a second HMAC round is consumed.\n\n"
            "**Verification:**\n"
            "Recompute the float, calculate each item's cumulative weight and "
            "find which item the float lands on — you'll get the exact same item."
        ),
    },
}


# ─── Main panel embed ─────────────────────────────────────────────────────────

def _overview_embed() -> discord.Embed:
    embed = discord.Embed(
        title="🔐 Provably Fair System",
        description=(
            "Every single game result on this server is **100% verifiable**.\n"
            "Select a game below to learn exactly how its outcome is calculated, "
            "or click **🔎 Verify** to check a result yourself.\n\n"
            "**Supported Games:**\n"
            + "\n".join(f"{v['emoji']} {v['label']}" for k, v in _GAMES.items() if k != "overview")
        ),
        color=0x5865f2,
    )
    embed.set_footer(text=FOOTER_TEXT)
    return embed


def _game_embed(game_key: str) -> discord.Embed:
    data = _GAMES.get(game_key, _GAMES["overview"])
    embed = discord.Embed(
        title=data["title"],
        description=data["desc"],
        color=data["color"],
    )
    embed.set_footer(text=f"{FOOTER_TEXT}  •  Provably Fair")
    return embed


# ─── Views ────────────────────────────────────────────────────────────────────

class FairnessSelect(Select):
    def __init__(self):
        options = [
            discord.SelectOption(
                label=v["label"],
                value=k,
                emoji=v["emoji"],
            )
            for k, v in _GAMES.items()
        ]
        super().__init__(
            placeholder="📖 Select a game to learn how its PF works...",
            options=options,
            min_values=1,
            max_values=1,
            custom_id="fairness_select",
        )

    async def callback(self, interaction: discord.Interaction):
        key = self.values[0]
        await interaction.response.send_message(
            embed=_game_embed(key),
            ephemeral=True,
        )


class VerifyModal(Modal, title="🔎 Verify a Game Result"):
    server_seed = TextInput(
        label="Server Seed",
        placeholder="The revealed server seed (from PF log channel)",
        style=discord.TextStyle.short,
        max_length=128,
    )
    client_seed = TextInput(
        label="Client Seed",
        placeholder="Your client seed",
        style=discord.TextStyle.short,
        max_length=128,
    )
    nonce = TextInput(
        label="Nonce",
        placeholder="The nonce used in that round (e.g. 42)",
        style=discord.TextStyle.short,
        max_length=10,
    )
    server_seed_hash = TextInput(
        label="Server Seed Hash (to verify integrity)",
        placeholder="SHA-256 hash shown before the game (optional)",
        style=discord.TextStyle.short,
        required=False,
        max_length=128,
    )

    async def on_submit(self, interaction: discord.Interaction):
        ss = self.server_seed.value.strip()
        cs = self.client_seed.value.strip()
        try:
            nc = int(self.nonce.value.strip())
        except ValueError:
            return await interaction.response.send_message(
                "❌ Nonce must be an integer.", ephemeral=True
            )

        # Hash integrity check
        computed_hash = hashlib.sha256(ss.encode()).hexdigest()
        provided_hash = self.server_seed_hash.value.strip()
        hash_ok = (not provided_hash) or (computed_hash.lower() == provided_hash.lower())

        # Compute HMAC and floats
        msg = f"{cs}:{nc}".encode()
        digest = _hmac.new(ss.encode(), msg, hashlib.sha256).digest()
        floats = [
            int.from_bytes(digest[i * 4:(i + 1) * 4], "big") / (2 ** 32)
            for i in range(8)
        ]
        full_hmac = _hmac.new(ss.encode(), msg, hashlib.sha256).hexdigest()

        float_lines = "\n".join(
            f"  float[{i}] = {f:.10f}" for i, f in enumerate(floats)
        )

        hash_status = (
            "✅ **Hash matches** — server seed is authentic."
            if hash_ok
            else "❌ **Hash mismatch** — server seed may have been tampered with!"
        )

        embed = discord.Embed(
            title="🔎 Verification Result",
            color=0x57f287 if hash_ok else 0xed4245,
        )
        embed.add_field(
            name="🔑 Server Seed Hash",
            value=f"`{computed_hash}`\n{hash_status}",
            inline=False,
        )
        embed.add_field(
            name="🔗 Full HMAC-SHA256",
            value=f"```{full_hmac}```",
            inline=False,
        )
        embed.add_field(
            name="📊 Generated Floats",
            value=f"```\n{float_lines}\n```",
            inline=False,
        )
        embed.add_field(
            name="ℹ️ How to use these floats",
            value=(
                "Match floats against the game's formula:\n"
                "• **Roulette / Dice**: `float[0] × range` = your value, `float[1] × range` = house\n"
                "• **Hot & Cold**: `float[0] ≥ 0.5` → Cold, else Hot\n"
                "• **Limbo**: `0.90 / float[0]` = result multiplier\n"
                "• **Towers / Crystals**: `float[i] × cols` = position on floor i\n"
                "• **Case Opening**: map float onto cumulative item weights"
            ),
            inline=False,
        )
        embed.set_footer(text=f"{FOOTER_TEXT}  •  Provably Fair Verification")
        await interaction.response.send_message(embed=embed, ephemeral=True)


class FairnessView(View):
    def __init__(self):
        super().__init__(timeout=None)
        self.add_item(FairnessSelect())
        verify_btn = discord.ui.Button(
            label="🔎 Verify a Result",
            style=discord.ButtonStyle.blurple,
            custom_id="fairness_verify_btn",
            row=1,
        )
        verify_btn.callback = self._on_verify
        self.add_item(verify_btn)

    async def _on_verify(self, interaction: discord.Interaction):
        await interaction.response.send_modal(VerifyModal())


# ─── Cog ──────────────────────────────────────────────────────────────────────

class FairnessCog(commands.Cog):
    def __init__(self, bot: commands.Bot):
        self.bot = bot

    @app_commands.command(
        name="fairness",
        description="Send the Provably Fair information panel to this channel.",
    )
    async def fairness(self, interaction: discord.Interaction):
        await interaction.response.send_message(
            embed=_overview_embed(),
            view=FairnessView(),
        )


async def setup(bot: commands.Bot):
    await bot.add_cog(FairnessCog(bot))
